#!/usr/bin/env bash
#
# scripts/anchor-check.sh — every in-page (#anchor) link in the tracked Markdown resolves to a real
# heading in the same file, and no anchor targets a slug two headings share.
#
# Why: a broken in-page anchor does not 404 — GitHub returns 200 and the page silently scrolls nowhere.
# It is the cross-document-pointer failure nothing else catches: claims-audit sees forbidden claims and
# dead shas, not anchors (docs/ROADMAP.md Harness backlog). This is the ANCHOR half of that gap; the
# rung-number half stays on the backlog.
#
# Slugs are DERIVED the GitHub (cmark-gfm) way, verified against the api.github.com/markdown renderer, not
# string-matched against a hardcoded expectation: lowercase; drop every char not in [a-z0-9_ -]; then each
# space -> '-' with NO collapsing (so "A — B" -> "a--b", "A - B" -> "a---b", exactly as GitHub renders).
# Headings inside ``` fenced code are ignored, so a `#` shell comment is never read as a heading.
#
# Two checks:
#   A. every `](#slug)` link has a heading whose derived slug == slug.
#   B. a slug generated by 2+ headings is ambiguous — GitHub appends '-1' to the repeat, so a bare
#      `(#slug)` link silently lands on the FIRST. A set comparison (A) collapses duplicates and cannot
#      see this; a per-slug COUNT can. Flagged ONLY when an anchor actually targets the shared slug —
#      undirected duplicate headings are harmless, and noise is what gets a check switched off.
#
# EXIT-CODE CONTRACT (the same contract claims-audit and test-clean carry — a gate whose failure is
# indistinguishable from its absence is not a gate):
#   0 clean; 1 findings (a link to a missing heading, or an anchor onto a colliding slug); 2 the check
#   could not run (not a git repo, or zero Markdown files examined). `make` collapses any recipe failure
#   to its own 2, so CI calls `bash scripts/anchor-check.sh` directly, never `make anchor-check` — the
#   reason CLAUDE.md's Process green-bar names the script.
set -euo pipefail
cd "$(dirname "$0")/.."

git rev-parse --git-dir >/dev/null 2>&1 || { echo "anchor-check: not a git repository" >&2; exit 2; }

fail=0
examined=0

# The sed rule below is taken from GitHub's own renderer (api.github.com/markdown), not guessed — three
# probes, each heading -> the id GitHub emitted:
#   "Harness backlog — the per-rung claims audit" -> harness-backlog--the-per-rung-claims-audit  (em-dash)
#   "Foo  Bar"                                     -> foo--bar                                    (two spaces)
#   "A - B"                                        -> a---b                                       (hyphen)
# So each space becomes ONE hyphen and consecutive spaces are NOT collapsed: it is `s/ /-/g`, never
# `s/ +/-/g`. Collapsing passes today only because every heading uses single spaces; the first em-dash
# heading an anchor targets would be reported broken while being fine. Do not restore the `+`.
slugify()  { tr 'A-Z' 'a-z' | sed -E 's/[^a-z0-9_ -]//g; s/ /-/g'; }
headings() { { awk '/^```/{fence=!fence; next} !fence && /^#{1,6} /{sub(/^#+[ \t]+/,""); print}' "$1" \
              | slugify | sed '/^$/d'; } || true; }
anchors()  { { awk '/^```/{fence=!fence; next} !fence' "$1" \
              | grep -oE '\]\(#[a-z0-9_-]+\)' | sed -E 's/^\]\(#//; s/\)$//' | sed '/^$/d' | sort -u; } || true; }

while IFS= read -r f; do
  [ -n "$f" ] || continue
  examined=$((examined + 1))
  slugs_all="$(headings "$f")"
  slugs_uniq="$(printf '%s\n' "$slugs_all" | sort -u)"
  anch="$(anchors "$f")"

  # A — every in-page anchor resolves to a heading in this file.
  while IFS= read -r a; do
    [ -n "$a" ] || continue
    printf '%s\n' "$slugs_uniq" | grep -qxF -- "$a" \
      || { echo "FAIL: $f: in-page link (#$a) resolves to no heading" >&2; fail=1; }
  done <<EOF
$anch
EOF

  # B — a targeted slug that 2+ headings generate: the link hits the wrong heading.
  dups="$(printf '%s\n' "$slugs_all" | sed '/^$/d' | sort | uniq -d)"
  while IFS= read -r d; do
    [ -n "$d" ] || continue
    printf '%s\n' "$anch" | grep -qxF -- "$d" || continue
    echo "FAIL: $f: slug '$d' is generated by 2+ headings AND a (#$d) link targets it — the link lands on the wrong one (GitHub appends -1)" >&2
    fail=1
  done <<EOF
$dups
EOF
done <<EOF
$(git ls-files '*.md')
EOF

# A "clean" printed by a check that examined nothing is a false pass (a skipped loop, an empty file list).
if [ "$examined" -eq 0 ]; then
  echo "anchor-check: examined 0 Markdown files — the check did not run (NOT a clean result)." >&2
  exit 2
fi

if [ "$fail" -ne 0 ]; then
  echo "anchor-check: FAILED — a link points at no heading, or an anchor targets a colliding slug (see above)." >&2
  exit 1   # findings — reserved so a caller can tell a fired gate from an absent one
fi
echo "anchor-check: clean — $examined Markdown files swept, every in-page anchor resolves to a unique heading."
