#!/usr/bin/env bash
#
# scripts/gen-rung-status.sh — regenerate the README per-rung status block IN PLACE, between the
# <!-- rung-status:start --> / <!-- rung-status:end --> markers, from docs/ROADMAP.md (the ladder + the
# phase map) and the rung-* git tags. Called by `make readme-sync`. NEVER hand-edit the block — a
# hand-kept rung table becomes a second ladder and drifts from ROADMAP; edit the ladder or the phase map
# in ROADMAP and re-run make readme-sync.
#
# Status is DERIVED, not kept: a rung-NN tag means landed ([x]); anything else is planned ([ ]). There is
# no third state — nothing checkable would back one. Idempotent: same ROADMAP + tags -> byte-identical
# README, so running readme-sync twice changes nothing.
set -euo pipefail
cd "$(dirname "$0")/.."
ROADMAP=docs/ROADMAP.md
README=README.md

# Landed rungs: the NN from each rung-NN tag, two-digit to match the ladder, space-padded for matching.
LANDED=" $(git tag -l 'rung-*' | sed 's/^rung-//' | sort | tr '\n' ' ') "

# The phase map (order preserved) from between its markers in ROADMAP.
PHASES="$(awk '/<!-- phase-map:start -->/{p=1;next} /<!-- phase-map:end -->/{p=0} p' "$ROADMAP" | grep -E '^- ' || true)"
[ -n "$PHASES" ] || { echo "gen-rung-status: no phase map found between the markers in $ROADMAP" >&2; exit 2; }

# Fail LOUD if the phase map and the ladder disagree — every ladder rung must map to exactly one phase, so
# a rung added to ROADMAP without being placed in a phase cannot silently vanish from the README.
LADDER_NN="$(grep -E '^[0-9][0-9] ' "$ROADMAP" | grep -oE '^[0-9][0-9]' | sort -u)"
MAP_NN="$(printf '%s\n' "$PHASES" | sed -E 's/^- [^:]*: *//' | tr ' ' '\n' | grep -E '^[0-9][0-9]$' | sort -u)"
if [ "$LADDER_NN" != "$MAP_NN" ]; then
  echo "gen-rung-status: the phase map and the ladder disagree (a rung is unmapped or extra):" >&2
  diff <(printf '%s\n' "$LADDER_NN") <(printf '%s\n' "$MAP_NN") >&2 || true
  exit 2
fi

# A rung's title is its FULL ladder entry — the "NN ..." line plus the indented continuation lines ROADMAP
# wraps it across, joined to one line (never just the first line, which cuts mid-phrase). NO truncation:
# the block is a list, GitHub wraps a long line itself, and a "…" would tell a beginner there is more they
# cannot see — the opposite of the point. The wording is ROADMAP's own; nothing here rewrites or shortens it.
rung_title() {
  awk -v n="$1" '
    found && (/^[0-9][0-9] / || /^```/) { print title; found=0; exit }
    found { sub(/^[ \t]+/, ""); title = title " " $0; next }
    $0 ~ ("^" n " ")                    { found=1; title=$0; next }
    END { if (found) print title }
  ' "$ROADMAP" | tr -s ' '
}

# Build the block into a temp, then inject it between the README markers.
tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
{
  echo "<!-- GENERATED by \`make readme-sync\` from docs/ROADMAP.md (ladder + phase map) and the rung-* git"
  echo "     tags. Do NOT edit by hand — re-running make readme-sync overwrites it. Edit ROADMAP instead. -->"
  printf '%s\n' "$PHASES" | while IFS= read -r line; do
    phase="$(printf '%s' "$line" | sed -E 's/^- ([^:]*):.*/\1/')"
    rungs="$(printf '%s' "$line" | sed -E 's/^- [^:]*: *//')"
    total=0; done=0; body=""
    for nn in $rungs; do
      total=$((total + 1))
      title="$(rung_title "$nn")"
      case "$LANDED" in *" $nn "*) mark='[x]'; done=$((done + 1)) ;; *) mark='[ ]' ;; esac
      body="${body}- ${mark} ${title}"$'\n'
    done
    echo
    echo "**${phase}** — ${done}/${total} landed"
    printf '%s' "$body"
  done
} > "$tmp"

grep -q '<!-- rung-status:start -->' "$README" || { echo "gen-rung-status: no rung-status markers in $README" >&2; exit 2; }
awk -v gen="$tmp" '
  /<!-- rung-status:start -->/ { print; while ((getline line < gen) > 0) print line; skip=1; next }
  /<!-- rung-status:end -->/   { skip=0; print; next }
  skip { next }
  { print }
' "$README" > "$README.tmp"
mv "$README.tmp" "$README"
echo "gen-rung-status: rung-status block regenerated in $README"
